# Generated by Django 5.0.6 on 2024-06-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название привычки')),
                ('place', models.CharField(max_length=255, verbose_name='Место, в котором необходимо выполнять привычку')),
                ('time', models.TimeField(verbose_name='Время, когда необходимо выполнять привычку')),
                ('action', models.CharField(max_length=50, verbose_name='Действие, которое представляет собой привычка')),
                ('is_useful', models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак полезной привычки')),
                ('is_pleasant', models.BooleanField(default=True, verbose_name='привычка, которую можно привязать к выполнению полезной привычки')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=10, verbose_name='Периодичность')),
                ('duration', models.DurationField(help_text='Продолжительность выполнения привычки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('reward', models.TextField(blank=True, default=None, null=True, verbose_name='Вознаграждение')),
                ('related_habit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Cоздатель привычки')),
            ],
            options={
                'verbose_name': 'Создание привычки',
                'verbose_name_plural': 'Создание привычек',
            },
        ),
    ]
