# Generated by Django 5.0.6 on 2024-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_habit_user_habit_bot_id_alter_habit_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='bot_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ТG_id пользователя'),
        ),
    ]
